use anyhow::Result;
use rusqlite::Connection;

/// Common trait for all relation types
pub trait Relation {
    fn create(&self, conn: &Connection) -> Result<()>;
    fn update(&self, conn: &Connection) -> Result<()>;
    fn delete(&self, conn: &Connection) -> Result<()>;
}


// CharacterEpisode struct removed - now generated by macro in character_episode_macro.rs
